// ─── Configuration des thèmes communautaires ─────────────────────────────────
import {
  Users, MessageSquare,
  Gem, Footprints, PartyPopper, HandHeart, Package,
  ShoppingBag, MapPin, Wrench,
} from 'lucide-react';
import type { ThemeConfig } from './_types';

export const THEME_CONFIG: Record<string, ThemeConfig> = {
  collectionneurs: {
    label: 'Collectionneurs',
    emoji: '🏆',
    bgGradient: 'from-amber-50 to-yellow-50',
    headerBg: 'bg-gradient-to-r from-amber-500 to-yellow-500',
    textColor: 'text-amber-700',
    borderColor: 'border-amber-200',
    accentBg: 'bg-amber-50',
    href: '/collectionneurs',
    description: 'Vendez, échangez, donnez ou recherchez des objets de collection.',
    icon: Gem,
  },
  promenades: {
    label: 'Promenades',
    emoji: '🥾',
    bgGradient: 'from-green-50 to-emerald-50',
    headerBg: 'bg-gradient-to-r from-green-500 to-emerald-500',
    textColor: 'text-green-700',
    borderColor: 'border-green-200',
    accentBg: 'bg-green-50',
    href: '/promenades',
    description: 'Partagez des balades, découvrez les sentiers autour de Biguglia.',
    icon: Footprints,
  },
  evenements: {
    label: 'Événements',
    emoji: '🎉',
    bgGradient: 'from-pink-50 to-rose-50',
    headerBg: 'bg-gradient-to-r from-pink-500 to-rose-500',
    textColor: 'text-pink-700',
    borderColor: 'border-pink-200',
    accentBg: 'bg-pink-50',
    href: '/evenements',
    description: 'Participez aux événements locaux et rencontrez les habitants.',
    icon: PartyPopper,
  },
  associations: {
    label: 'Associations',
    emoji: '🤝',
    bgGradient: 'from-blue-50 to-sky-50',
    headerBg: 'bg-gradient-to-r from-blue-500 to-sky-500',
    textColor: 'text-blue-700',
    borderColor: 'border-blue-200',
    accentBg: 'bg-blue-50',
    href: '/associations',
    description: 'Rejoignez des associations locales, devenez bénévole.',
    icon: HandHeart,
  },
  'coups-de-main': {
    label: 'Coups de main',
    emoji: '🙌',
    bgGradient: 'from-orange-50 to-amber-50',
    headerBg: 'bg-gradient-to-r from-orange-500 to-amber-500',
    textColor: 'text-orange-700',
    borderColor: 'border-orange-200',
    accentBg: 'bg-orange-50',
    href: '/coups-de-main',
    description: 'Entraidez-vous : proposez ou demandez un coup de main.',
    icon: HandHeart,
  },
  materiel: {
    label: 'Matériel',
    emoji: '🔧',
    bgGradient: 'from-teal-50 to-cyan-50',
    headerBg: 'bg-gradient-to-r from-teal-500 to-cyan-500',
    textColor: 'text-teal-700',
    borderColor: 'border-teal-200',
    accentBg: 'bg-teal-50',
    href: '/materiel',
    description: 'Prêtez ou empruntez du matériel entre voisins.',
    icon: Package,
  },
  annonces: {
    label: 'Annonces',
    emoji: '📢',
    bgGradient: 'from-violet-50 to-purple-50',
    headerBg: 'bg-gradient-to-r from-violet-500 to-purple-500',
    textColor: 'text-violet-700',
    borderColor: 'border-violet-200',
    accentBg: 'bg-violet-50',
    href: '/annonces',
    description: 'Achetez, vendez ou donnez des objets localement.',
    icon: ShoppingBag,
  },
  'perdu-trouve': {
    label: 'Perdu / Trouvé',
    emoji: '🔍',
    bgGradient: 'from-red-50 to-rose-50',
    headerBg: 'bg-gradient-to-r from-red-500 to-rose-500',
    textColor: 'text-red-700',
    borderColor: 'border-red-200',
    accentBg: 'bg-red-50',
    href: '/perdu-trouve',
    description: 'Signalez un objet perdu ou trouvé à Biguglia.',
    icon: MapPin,
  },
  forum: {
    label: 'Forum',
    emoji: '💬',
    bgGradient: 'from-indigo-50 to-blue-50',
    headerBg: 'bg-gradient-to-r from-indigo-500 to-blue-500',
    textColor: 'text-indigo-700',
    borderColor: 'border-indigo-200',
    accentBg: 'bg-indigo-50',
    href: '/forum',
    description: 'Discussions libres entre habitants de Biguglia.',
    icon: MessageSquare,
  },
  artisans: {
    label: 'Artisans',
    emoji: '🔨',
    bgGradient: 'from-orange-50 to-amber-50',
    headerBg: 'bg-gradient-to-r from-orange-500 to-amber-500',
    textColor: 'text-orange-700',
    borderColor: 'border-orange-200',
    accentBg: 'bg-orange-50',
    href: '/artisans',
    description: 'Artisans vérifiés de Biguglia — SIRET, assurance, avis.',
    icon: Wrench,
  },
};

export const DEFAULT_THEME: ThemeConfig = {
  label: 'Communauté',
  emoji: '🏘️',
  bgGradient: 'from-gray-50 to-slate-50',
  headerBg: 'bg-gradient-to-r from-gray-500 to-slate-500',
  textColor: 'text-gray-700',
  borderColor: 'border-gray-200',
  accentBg: 'bg-gray-50',
  href: '/',
  description: 'Communauté locale de Biguglia.',
  icon: Users,
};

export function getThemeConfig(slug: string): ThemeConfig {
  return THEME_CONFIG[slug] ?? DEFAULT_THEME;
}
